version: '3'
services:
  proxy:
    image: 'traefik:v3.0'
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '443:443'
      - '8080:8080'
    networks:
      default:
        aliases:
          - ${HOST_NAME}

  web_api:
    extends:
      file: ../api/compose.yml
      service: api
    depends_on:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.web-api.rule=Host(`${HOST_NAME}`) && PathPrefix(`/api`)'
      - 'traefik.http.middlewares.web-api-replacepath.replacepathregex.regex=^/api/(.*)'
      - 'traefik.http.middlewares.web-api-replacepath.replacepathregex.replacement=/$$1'
      - 'traefik.http.routers.web-api.middlewares=web-api-replacepath'
      - 'traefik.http.services.web_api.loadbalancer.server.port=8000'

  web:
    image: node:20.10-alpine
    working_dir: /app
    command:
      - npm
      - run
      - dev
      - --prefix ../web
    volumes:
      - ../web:/app
    depends_on:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.web.rule=Host(`${HOST_NAME}`)'
      - 'traefik.http.services.web.loadbalancer.server.port=3000'

networks:
  laravel:
    driver: bridge